back/config/routes.rb
Rails.application.routes.draw do

  resources :contatos
  resources :acessos

  match '/acessosCreate', to: 'acessos#create', :via => [:get, :post]
  match '/contatosCreate', to: 'contatos#create', :via => [:get, :post]

  get 'home/index'
 

  root 'home#index'

end

back/app/models/acesso.rb
class Acesso < ActiveRecord::Base
	belongs_to :contato
end

back/app/models/contato.rb
class Contato < ActiveRecord::Base
end

back/app/controllers/acessos_controller.rb
class AcessosController < ApplicationController
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def new
  end

  def index
    @acesso = Acesso.order('created_at DESC').limit(50)
  end

  def show
    @acesso = Acesso.find(params[:id])
  end

  def create
  if Contato.exists?(id: acesso_params[:contato_id])
     @acesso = Acesso.new(acesso_params)
    @acesso.save
    render :json => { :status => 'ok', :acesso => @acesso.as_json }
    else
      render :json => { :status => 'error', :error => 'contato não encontrado' }
     end
  end

  private
  def acesso_params
    params.require(:acessos).permit(:pagina, :contato_id)
  end

  # For all responses in this controller, return the CORS access control headers.

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    if request.method == :options
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
      headers['Access-Control-Max-Age'] = '1728000'
      render :text => '', :content_type => 'text/plain'
    end
  end
  
end

back/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

back/app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def new
  end

  def index
    @contato = Contato.order('created_at DESC').limit(50)
  end

  def show
    if Contato.exists?(id: params[:id])
      @contato = Contato.find(params[:id])
      render :json => { status: 'ok', :contato => contato.to_json }
    else
      render :json => { status: 'error', :error => 'contato não encontrado' }
    end
  end

  def create
    if Contato.exists?(email: contato_params[:email])
      @contato = Contato.find_by_email(contato_params[:email])
      render :json => { status: 'error', :error => 'contato já existente', :contato => @contato.as_json } 
    else
      @contato = Contato.new(contato_params)
      @contato.save
      render :json => { status: 'ok', :contato => @contato.as_json } 
    end

  end

  private
  def contato_params
    params.require(:contatos).permit(:nome, :email)
  end

    # For all responses in this controller, return the CORS access control headers.
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.
  def cors_preflight_check
    if request.method == :options
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
      headers['Access-Control-Max-Age'] = '1728000'
      render :text => '', :content_type => 'text/plain'
    end
  end

end

back/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

back/app/helpers/acessos_helper.rb
module AcessosHelper
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/contatos_helper.rb
module ContatosHelper
end

back/app/helpers/home_helper.rb
module HomeHelper
end

back/app/views/acessos/index.html.erb
 
<table cellspacing="3" border="1" cellpadding:"7" align="center" width="70%">
  <tr>
    <td colspan="6" align="center"><h1>Listagem de acessos</h1></td>
  </tr>
  <tr>
    <th>ID</th>
    <th>Pagina</th>
    <th>ID_contato</th>
    <th>Contato_Nome</th>
    <th>Contato_Email</th>
    <th>Created_at</th>
  </tr>
 
  <% @acesso.each do |access| %>
    <tr>
      <td><%= access.id %></td>
      <td><%= access.pagina %></td>
      <td><%= access.contato.id %></td>
      <td><%= access.contato.nome %></td>
      <td><%= access.contato.email %></td>
      <td><%= access.created_at.strftime("%d/%m/%Y %T") %></td>
    </tr>
  <% end %>
</table>

back/app/views/acessos/new.html.erb
<h1>Novo Acesso</h1>

<%= form_for :acesso, url: acessos_path do |f| %>
  <p>
    <%= f.label :pagina %><br>
    <%= f.text_field :pagina %>
  </p>
 
  <p>
    <%= f.label :contato_id %><br>
    <%= f.text_field :contato_id %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

back/app/views/acessos/show.html.erb
<h1>Detalhes do Acesso</h1>
 
<p>
  <strong>ID:</strong>
  <%= @acesso.id %>
</p>
 
<p>
  <strong>Pagina:</strong>
  <%= @acesso.pagina %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @acesso.contato.nome %>
</p>

back/app/views/contatos/index.html.erb
<table cellspacing="3" border="1" cellpadding:"7" align="center" width="70%">
  <tr>
    <td colspan="6" align="center"><h1>Listagem de Contatos</h1></td>
  </tr>
  <tr>
    <th>ID</th>
    <th>Nome</th>
    <th>Email</th>
    <th>Created_at</th>
  </tr>
 
  <% @contato.each do |cont| %>
    <tr>
      <td><%= cont.id %></td>
      <td><%= cont.nome %></td>
      <td><%= cont.email %></td>
      <td><%= cont.created_at.strftime("%d/%m/%Y %T") %></td>
    </tr>
  <% end %>
</table>

back/app/views/contatos/new.html.erb
<h1>Novo Contato</h1>

<%= form_for :contato, url: contatos_path do |f| %>
  <p>
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

back/app/views/contatos/show.html.erb
<%= @contato.to_json %>

back/app/views/home/index.html.erb
<h1>Home Index!</h1>

back/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTeste</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>